"""empty message

Revision ID: 60d713c2ffde
Revises: f46ef8baf40a
Create Date: 2023-10-14 01:03:25.344693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d713c2ffde'
down_revision = 'f46ef8baf40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videojuego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.String(length=250), nullable=False),
    sa.Column('anio_lanzmaineto', sa.String(length=250), nullable=False),
    sa.Column('estudio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videojuego')
    # ### end Alembic commands ###
