"""empty message

Revision ID: f46ef8baf40a
Revises: 34c5d804dbd5
Create Date: 2023-10-12 00:35:44.030843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46ef8baf40a'
down_revision = '34c5d804dbd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('logo', sa.String(length=250), nullable=False),
    sa.Column('slogan', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estudio')
    # ### end Alembic commands ###
